---
# Source: hami-dra-driver/templates/rbac-kubeletplugin.yaml.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hami-dra-driver-service-account-kubeletplugin
  namespace: default
  labels:
    helm.sh/chart: hami-dra-driver-0.1.0
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hami-dra-driver
    app.kubernetes.io/instance: hami-dra-driver
---
# Source: hami-dra-driver/templates/rbac-kubeletplugin.yaml.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hami-dra-driver-clusterrole-kubeletplugin
  labels:
    helm.sh/chart: hami-dra-driver-0.1.0
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hami-dra-driver
    app.kubernetes.io/instance: hami-dra-driver
rules:
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceslices"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
# Source: hami-dra-driver/templates/rbac-kubeletplugin.yaml.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hami-dra-driver-clusterrole-binding-kubeletplugin
  labels:
    helm.sh/chart: hami-dra-driver-0.1.0
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hami-dra-driver
    app.kubernetes.io/instance: hami-dra-driver
subjects:
- kind: ServiceAccount
  name: hami-dra-driver-service-account-kubeletplugin
  namespace: default
roleRef:
  kind: ClusterRole
  name: hami-dra-driver-clusterrole-kubeletplugin
  apiGroup: rbac.authorization.k8s.io
---
# Source: hami-dra-driver/templates/rbac-kubeletplugin.yaml.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hami-dra-driver-role-kubeletplugin
  namespace: default
  labels:
    helm.sh/chart: hami-dra-driver-0.1.0
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hami-dra-driver
    app.kubernetes.io/instance: hami-dra-driver
---
# Source: hami-dra-driver/templates/rbac-kubeletplugin.yaml.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hami-dra-driver-role-binding-kubeletplugin
  namespace: default
  labels:
    helm.sh/chart: hami-dra-driver-0.1.0
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hami-dra-driver
    app.kubernetes.io/instance: hami-dra-driver
subjects:
- kind: ServiceAccount
  name: hami-dra-driver-service-account-kubeletplugin
  namespace: default
roleRef:
  kind: Role
  name: hami-dra-driver-role-kubeletplugin
  apiGroup: rbac.authorization.k8s.io
---
# Source: hami-dra-driver/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hami-dra-driver-kubelet-plugin
  namespace: default
  labels:
    helm.sh/chart: hami-dra-driver-0.1.0
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hami-dra-driver
    app.kubernetes.io/instance: hami-dra-driver
spec:
  selector:
    matchLabels:
      hami-dra-driver-component: kubelet-plugin
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hami-dra-driver
        app.kubernetes.io/instance: hami-dra-driver
        hami-dra-driver-component: kubelet-plugin
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: hami-dra-driver-service-account
      initContainers:
      - name: init-container
        image: "projecthami/k8s-dra-driver:v0.1.0"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: [bash, /usr/bin/kubelet-plugin-prestart.sh]
        env:
        - name: NVIDIA_DRIVER_ROOT
          value: "/"
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        - name: KUBELET_REGISTRAR_DIRECTORY_PATH
          value: "/var/lib/kubelet/plugins_registry"
        - name: KUBELET_PLUGINS_DIRECTORY_PATH
          value: "/var/lib/kubelet/plugins"
        volumeMounts:
        - name: driver-root-parent
          mountPath: /driver-root-parent
          readOnly: true
      containers:
      - name: gpus
        image: "projecthami/k8s-dra-driver:v0.1.0"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["bash", "-c"]
        args:
        - |-
          # Conditionally mask the params file to prevent this container from
          # recreating any missing GPU device nodes. This is necessary, for
          # example, when running under nvkind to limit the set GPUs governed
          # by the plugin even though it has cgroup access to all of them.
          if [ "${MASK_NVIDIA_DRIVER_PARAMS}" = "true" ]; then
            cp /proc/driver/nvidia/params root/gpu-params
            sed -i 's/^ModifyDeviceFiles: 1$/ModifyDeviceFiles: 0/' root/gpu-params
            mount --bind root/gpu-params /proc/driver/nvidia/params
          fi
          hami-kubelet-plugin -v $(LOG_VERBOSITY)
        startupProbe:
          grpc:
            port: 51516
            service: liveness
          failureThreshold: 60
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          grpc:
            port: 51516
            service: liveness
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 10
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "/usr/bin/vgpu-init.sh /usr/local/vgpu"]
        env:
        - name: LOG_VERBOSITY
          value: "4"
        - name: MASK_NVIDIA_DRIVER_PARAMS
          value: "false"
        - name: NVIDIA_DRIVER_ROOT
          value: "/"
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        - name: CDI_ROOT
          value: "/var/run/cdi"
        - name: NVIDIA_MIG_CONFIG_DEVICES
          value: all
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IMAGE_NAME
          value: "projecthami/k8s-dra-driver:v0.1.0"
        - name: KUBELET_REGISTRAR_DIRECTORY_PATH
          value: "/var/lib/kubelet/plugins_registry"
        - name: KUBELET_PLUGINS_DIRECTORY_PATH
          value: "/var/lib/kubelet/plugins"
        - name: HEALTHCHECK_PORT
          value: "51516"
        volumeMounts:
        - name: plugins-registry
          mountPath: "/var/lib/kubelet/plugins_registry"
        - name: plugins
          mountPath: "/var/lib/kubelet/plugins"
          mountPropagation: Bidirectional
        - name: cdi
          mountPath: "/var/run/cdi"
        - name: driver-root
          mountPath: /driver-root
          mountPropagation: HostToContainer
        - name: host-vgpu
          mountPath: "/usr/local/vgpu"
        - name: host-tmp
          mountPath: "/tmp"
      volumes:
      - name: plugins-registry
        hostPath:
          path: "/var/lib/kubelet/plugins_registry"
          type: ""
      - name: plugins
        hostPath:
          path: "/var/lib/kubelet/plugins"
          type: ""
      - name: cdi
        hostPath:
          path: "/var/run/cdi"
          type: ""
      - name: driver-root-parent
        hostPath:
          path: "/"
          type: DirectoryOrCreate
      - name: driver-root
        hostPath:
          path: "/"
          type: DirectoryOrCreate
      - name: host-vgpu
        hostPath:
          path: "/usr/local/vgpu"
          type: DirectoryOrCreate
      - name: host-tmp
        hostPath:
          path: "/tmp"
          type: ""
---
# Source: hami-dra-driver/templates/deviceclass-hami-gpu.yaml
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: hami-core-gpu.projet-hami.io
  labels:
    helm.sh/chart: hami-dra-driver-0.1.0
    app.kubernetes.io/version: "v0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hami-dra-driver
    app.kubernetes.io/instance: hami-dra-driver
spec:
  selectors:
  - cel:
      expression: "device.driver == 'hami-core-gpu.project-hami.io' && device.attributes['hami-core-gpu.project-hami.io'].type == 'hami-gpu')"
  extendedResourceName: nvidia.com/gpu
