name: "CI"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'demo/**'
      - 'imgs/**'
  pull_request:
    branches: [ main ]
    types:
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - 'README.md'
      - 'demo/**'
      - 'imgs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.1'

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.6
